### PR TITLE
Fix autonomous turning.

### LINKED ISSUE #48: Autonomous Turning
The way HeadingSensor.yaw works, when it reaches 360 or -360 degrees, it resets back to 0. This is a problem if, for example, you are already at 300 degrees and you try to turn 90 degrees, becuase the robot will continue to spin until it hits 390 degrees, which will never happen.

### PR DESCRIPTION
**Pull request by amackworth**
Resolves #48.

### CODE REVIEW

**Comment by AidanSmith** [comment]
Absolute Yaw works on the practice robot. I changed the autonomous turning code to use absolute yaw instead of regular yaw. I believe it will work now.

File: QuasarHelios2015/src/org/team1540/quasarhelios/HeadingSensor.java [hunk 1]
```diff
@@ -32,6 +39,26 @@ public static void setup() {
...
+
+        Igneous.globalPeriodic.send(new EventOutput() {
+            public void event() {
+                float currentyaw = yaw.get();
+                float oldyaw = oldYaw.get();
+                if (Math.abs(currentyaw - oldyaw) > 180) {
+                    if (oldyaw > 180) {
+                        accumulator.set(accumulator.get() + 1);
+                    } else if (oldyaw < -180) {
+                        accumulator.set(accumulator.get() - 1);
```
Comment (celskeggs) [inline QuasarHelios2015/src/org/team1540/quasarhelios/HeadingSensor.java]: You could add multiples of 360 here and then not have to multiply.

File: QuasarHelios2015/src/org/team1540/quasarhelios/HeadingSensor.java [hunk 2]
```diff
@@ -32,6 +39,26 @@ public static void setup() {
 
         zeroGyro = sensor.zeroGyro;
 
+        absoluteYaw = FloatMixing.addition.of(FloatMixing.multiplication.of((FloatInput) accumulator, 360), yaw);
+
+        Igneous.globalPeriodic.send(new EventOutput() {
+            public void event() {
+                float currentyaw = yaw.get();
+                float oldyaw = oldYaw.get();
```
Comment (celskeggs) [inline QuasarHelios2015/src/org/team1540/quasarhelios/HeadingSensor.java]: `oldyaw` might make sense as an instance variable on this anonymous class instead of as a FloatStatus.

File: QuasarHelios2015/src/org/team1540/quasarhelios/HeadingSensor.java [hunk 3]
```diff
@@ -32,6 +39,26 @@ public static void setup() {
...
+                    } else if (oldyaw < -180) {
+                        accumulator.set(accumulator.get() - 1);
+                    }
+                }
+                oldYaw.set(yaw.get());
+            }
+        });
+
+        Cluck.publish("Accumulator", accumulator);
+        Cluck.publish("Absolute Yaw", absoluteYaw);
```
Comment (celskeggs) [inline QuasarHelios2015/src/org/team1540/quasarhelios/HeadingSensor.java]: Maybe these names could be qualified better to make it clear what they're talking about.

**Comment by celskeggs** [comment]
That's what I see right now.

**Comment by AidanSmith** [comment]
I updated the drive code to also use absolute yaw for keeping straight. I kept field centric using regular yaw.

**Comment by AidanSmith** [comment]
I have tested new heading control drive code on practice robot.

File: QuasarHelios2015/src/org/team1540/quasarhelios/HeadingSensor.java [hunk 4]
```diff
@@ -17,6 +19,12 @@
 
     public static EventOutput zeroGyro;
 
+    private static final FloatStatus accumulator = new FloatStatus();
+
+    public static FloatInput absoluteYaw;
+
+    public static final EventOutput resetAccumulator = FloatMixing.getSetEvent(accumulator, 0);
```
Comment (celskeggs) [inline QuasarHelios2015/src/org/team1540/quasarhelios/HeadingSensor.java]: You can call this directly on the FloatStatus.

**Comment by celskeggs** [comment]
Besides that, looks good.

**Comment by AidanSmith** [comment]
Fixed.

**Comment by AidanSmith** [comment]
I switched it back.

**Comment by AidanSmith** [comment]
I also merged master into it, by the way.

**Comment by celskeggs** [comment]
Looks good. Will this break anything if we merge it?

**Comment by AidanSmith** [comment]
I don’t believe it will break anything.

**Comment by celskeggs** [comment]
Great.
